import wikipedia
from googlesearch import search
import requests
from bs4 import BeautifulSoup
import json
import os
import re
from functools import lru_cache
from llm import generate_llm

MEMORY_FILE = "memory.json"

def load_memory():
    if not os.path.exists(MEMORY_FILE):
        return {}
    try:
        with open(MEMORY_FILE, "r") as f:
            data = json.load(f)
            return data if isinstance(data, dict) else {}
    except:
        return {}

def save_memory(memory):
    with open(MEMORY_FILE, "w") as f:
        json.dump(memory, f, indent=2)

def add_memory(user_input):
    memory = load_memory()

    match = re.search(r"my name is (\w+)", user_input.lower())
    if match:
        memory["name"] = match.group(1).capitalize()
        save_memory(memory)
        return f"💾 I'll remember your name is {memory['name']}."

    return ""

def get_memory(query):
    memory = load_memory()
    if "name" in query.lower() and "name" in memory:
        return memory["name"]
    return None
@lru_cache(maxsize=100)
def retrieve(query):
    try:
        with open("data/knowledge.txt", "r", encoding="utf-8") as f:
            docs = f.readlines()
    except:
        return None

    for doc in docs:
        if "-" in doc:
            key, val = doc.split("-", 1)
            if key.strip().lower() in query.lower():
                return val.strip()

    return None

@lru_cache(maxsize=50)
def web_search(query):
    try:
        results = wikipedia.search(query)
        if results:
            return wikipedia.summary(results[0], sentences=2)
    except:
        pass

    return None  #  skip heavy scraping for speed

def quick_reflect(answer, source):
    if source == "MEMORY":
        return "Memory used"
    if source == "RAG":
        return "Knowledge base used"
    if source == "WEB":
        return "Web data used"
    if source == "LLM":
        return " Generated by AI"
    return ""